FROM erebe/qovery-test:latest

WORKDIR /app

ARG QOVERY_PROJECT_ID

#RUN sleep 99999999999
COPY . .
#RUN while true; do echo sleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeping; sleep 0.1; done

RUN pip install simple-websocket-server grpcio-tools

CMD [ "python3", "app.py"]

#CMD [ "/bin/sh", "-c", "sleep 999999"]
