# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsrv.proto\"-\n\x0b\x43lientInput\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t21\n\x07Greeter\x12&\n\x05greet\x12\x0c.ClientInput\x1a\r.ServerOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'srv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTINPUT._serialized_start=13
  _CLIENTINPUT._serialized_end=58
  _SERVEROUTPUT._serialized_start=60
  _SERVEROUTPUT._serialized_end=91
  _GREETER._serialized_start=93
  _GREETER._serialized_end=142
# @@protoc_insertion_point(module_scope)
